export const SUGGESTED_PROFILE_REQUEST = 'SUGGESTED_PROFILE_REQUEST'
export const SUGGESTED_PROFILE_SUCCESS = 'SUGGESTED_PROFILE_SUCCESS'
export const SUGGESTED_PROFILE_ERROR = 'SUGGESTED_PROFILE_ERROR'

