export const SEARCH_MODAL_OPEN = 'SEARCH_MODAL_OPEN';
export const SEARCH_MODAL_CLOSE = "SEARCH_MODAL_CLOSE"

export const SETTINGS_MODAL_OPEN = 'SETTIMGS_MODAL_OPEN';
export const SETTINGS_MODAL_CLOSE = "SETTIMGS_MODAL_CLOSE"

export const ACTIVITY_MODAL_OPEN = 'ACTIVITY_MODAL_OPEN';
export const ACTIVITY_MODAL_CLOSE = "ACTIVITY_MODAL_CLOSE"

export const POST_UPDLOAD_MODAL_OPEN = 'POST_UPDLOAD_MODAL_OPEN';
export const POST_UPDLOAD_MODAL_CLOSE = "POST_UPDLOAD_MODAL_CLOSE"