export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILS = 'GET_PROFILE_FAILS'

export const GET_CURRENT_PROFILE_POSTS_REQUEST = 'GET_CURRENT_PROFILE_POSTS_REQUEST'
export const GET_CURRENT_PROFILE_POSTS_SUCCESS = 'GET_CURRENT_PROFILE_POSTS_SUCCESS'
export const GET_CURRENT_PROFILE_POSTS_FAILS = 'GET_CURRENT_PROFILE_POSTS_FAILS'